# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name_plural': 'messages',
                'verbose_name': 'message',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('question', models.TextField(max_length='300', verbose_name='question')),
                ('answer_time', models.IntegerField(blank=True, null=True, verbose_name='answer time')),
                ('answered', models.BooleanField(default=False, verbose_name='answered')),
            ],
            options={
                'verbose_name_plural': 'questions',
                'verbose_name': 'question',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('cod_reunion', models.CharField(blank=True, max_length=200, null=True, verbose_name='code reunion')),
                ('title_reunion', models.CharField(blank=True, max_length=200, null=True, verbose_name='title reunion')),
                ('legislative_body_initials', models.CharField(blank=True, max_length=200, null=True, verbose_name='legislative body initials')),
                ('legislative_body_alias', models.CharField(blank=True, max_length=200, null=True, verbose_name='legislative body alias')),
                ('legislative_body', models.TextField(blank=True, null=True, verbose_name='legislative body')),
                ('reunion_status', models.IntegerField(choices=[(1, 'Não Confirmada'), (2, 'Convocada'), (3, 'Em Andamento'), (4, 'Encerrada'), (5, 'Cancelada'), (6, 'Suspensa'), (7, 'Encerrada (Termo)'), (8, 'Encerrada (Final)'), (9, 'Encerrada(Comunicado)')], default=1, verbose_name='reunion status')),
                ('reunion_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='reunion type')),
                ('reunion_object', models.TextField(blank=True, null=True, verbose_name='reunion object')),
                ('reunion_theme', models.TextField(blank=True, null=True, verbose_name='reunion theme')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='location')),
                ('is_joint', models.BooleanField(default=False, verbose_name='is joint')),
                ('youtube_status', models.IntegerField(choices=[(0, 'Sem transmissão'), (1, 'Em andamento'), (2, 'Transmissão encerrada')], default=0, verbose_name='youtube status')),
                ('youtube_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='youtube id')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('online_users', models.IntegerField(default=0, verbose_name='online users')),
                ('max_online_users', models.IntegerField(default=0, verbose_name='max online users')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('is_visible', models.BooleanField(default=False, verbose_name='is visible')),
            ],
            options={
                'verbose_name_plural': 'rooms',
                'verbose_name': 'room',
            },
        ),
        migrations.CreateModel(
            name='UpDownVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('vote', models.BooleanField(choices=[(True, 'Up Vote'), (False, 'Down Vote')], default=False, verbose_name='vote')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.Question', verbose_name='question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'votes',
                'verbose_name': 'vote',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.Room', verbose_name='room'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Room', verbose_name='room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='updownvote',
            unique_together=set([('user', 'question')]),
        ),
    ]
