# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_is_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='answer time'),
        ),
    ]
