# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'agenda', 'verbose_name_plural': 'agendas'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
