# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_to_new_video(apps, schema_editor):
    Room = apps.get_model("core", "Room")
    Video = apps.get_model("core", "Video")

    for room in Room.objects.filter(youtube_id__isnull=False):
        video = Video()
        video.room = room
        video.video_id = room.youtube_id
        video.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roomattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('video_id', models.CharField(max_length=200, verbose_name='youtube id')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('is_attachment', models.BooleanField(default=False, verbose_name='is_attachment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.Room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.RunPython(
            migrate_to_new_video
        ),
        migrations.RemoveField(
            model_name='room',
            name='youtube_id',
        ),
    ]
