# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roomattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
    ]
