# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161013_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoId',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
