# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161017_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='updownvote',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.Question'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='updownvote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='updownvote',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='updownvote',
            name='object_pk',
        ),
    ]
