# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 16:09
from __future__ import unicode_literals

from django.db import migrations


def refactor_title_reunion(apps, schema_editor):
    Room = apps.get_model("core", "Room")

    for room in Room.objects.all():
        if not room.is_joint:
            room.title_reunion = room.legislative_body_alias
            room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180419_1120'),
    ]

    operations = [
        migrations.RunPython(
            refactor_title_reunion
        ),
        migrations.RemoveField(
            model_name='room',
            name='cod_audio',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_joint',
        ),
        migrations.RemoveField(
            model_name='room',
            name='legislative_body_alias',
        ),
        migrations.RemoveField(
            model_name='room',
            name='reunion_status',
        ),
    ]
