# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20161021_1715'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='updownvote',
            unique_together=set([('user', 'question')]),
        ),
    ]
