# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 14:30
from __future__ import unicode_literals

from django.db import migrations, models


def add_video_id(apps, schema_editor):
    Question = apps.get_model("core", "Question")

    for question in Question.objects.all():
        if question.room.videos.all():
            question.video_id = question.room.videos.last().video_id
            question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180424_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='video id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=300, verbose_name='question'),
        ),
        migrations.RunPython(
            add_video_id
        ),
    ]
