# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161110_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
