# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180425_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video_id',
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.Video', verbose_name='video'),
        ),
    ]
