# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161123_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
