# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_video_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
