# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161123_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length='240'),
        ),
    ]
