# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170116_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length='600'),
        ),
    ]
