# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170220_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='legislative_body',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='legislative_body_alias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='legislative_body_initials',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='legislative_body_type',
            field=models.IntegerField(choices=[(1, 'Comissão Diretora'), (2, 'Comissão Permanente'), (3, 'Comissão Especial'), (4, 'Comissão Parlamentar de Inquérito'), (5, 'Comissão Externa'), (6, 'Comissão Mista Permanente'), (11, 'Conselho')], default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='reunion_object',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='reunion_status',
            field=models.IntegerField(choices=[(1, 'Não Confirmada'), (2, 'Convocada'), (3, 'Em Andamento'), (4, 'Encerrada'), (5, 'Cancelada'), (6, 'Suspensa'), (7, 'Encerrada (Termo)'), (8, 'Encerrada (Final)'), (9, 'Encerrada(Comunicado)')], default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='reunion_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='subcommission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='title_reunion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='cod_reunion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
