# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170214_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cod_reunion',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
