# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170331_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='youtube_status',
            field=models.IntegerField(choices=[(0, 'Sem transmissão'), (1, 'Em andamento'), (2, 'Transmissão encerrada')], default=1, max_length=20),
        ),
    ]
