# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_room_youtube_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='video',
        ),
        migrations.RemoveField(
            model_name='room',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='room',
            name='video',
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
