# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170403_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AddField(
            model_name='room',
            name='is_joint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='legislative_body_type',
            field=models.IntegerField(choices=[(1, 'Comissão Diretora'), (2, 'Comissão Permanente'), (3, 'Comissão Especial'), (4, 'Comissão Parlamentar de Inquérito'), (5, 'Comissão Externa'), (6, 'Comissão Mista Permanente'), (11, 'Conselho')], default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='reunion_status',
            field=models.IntegerField(choices=[(1, 'Não Confirmada'), (2, 'Convocada'), (3, 'Em Andamento'), (4, 'Encerrada'), (5, 'Cancelada'), (6, 'Suspensa'), (7, 'Encerrada (Termo)'), (8, 'Encerrada (Final)'), (9, 'Encerrada(Comunicado)')], default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='youtube_status',
            field=models.IntegerField(choices=[(0, 'Sem transmissão'), (1, 'Em andamento'), (2, 'Transmissão encerrada')], default=0),
        ),
    ]
