# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170418_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
