# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_question_answered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updownvote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'votes'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='room',
            name='legislative_body_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='subcommission',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Room', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='answer time'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='answered'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length='600', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.Room', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='room',
            name='cod_reunion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='code reunion'),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_joint',
            field=models.BooleanField(default=False, verbose_name='is joint'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='is visible'),
        ),
        migrations.AlterField(
            model_name='room',
            name='legislative_body',
            field=models.TextField(blank=True, null=True, verbose_name='legislative body'),
        ),
        migrations.AlterField(
            model_name='room',
            name='legislative_body_alias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='legislative body alias'),
        ),
        migrations.AlterField(
            model_name='room',
            name='legislative_body_initials',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='legislative body initials'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_online_users',
            field=models.IntegerField(default=0, verbose_name='max online users'),
        ),
        migrations.AlterField(
            model_name='room',
            name='online_users',
            field=models.IntegerField(default=0, verbose_name='online users'),
        ),
        migrations.AlterField(
            model_name='room',
            name='reunion_object',
            field=models.TextField(blank=True, null=True, verbose_name='reunion object'),
        ),
        migrations.AlterField(
            model_name='room',
            name='reunion_status',
            field=models.IntegerField(choices=[(1, 'Não Confirmada'), (2, 'Convocada'), (3, 'Em Andamento'), (4, 'Encerrada'), (5, 'Cancelada'), (6, 'Suspensa'), (7, 'Encerrada (Termo)'), (8, 'Encerrada (Final)'), (9, 'Encerrada(Comunicado)')], default=1, verbose_name='reunion status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='reunion_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='reunion type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title_reunion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title reunion'),
        ),
        migrations.AlterField(
            model_name='room',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='room',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='youtube id'),
        ),
        migrations.AlterField(
            model_name='room',
            name='youtube_status',
            field=models.IntegerField(choices=[(0, 'Sem transmissão'), (1, 'Em andamento'), (2, 'Transmissão encerrada')], default=0, verbose_name='youtube status'),
        ),
        migrations.AlterField(
            model_name='updownvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.Question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='updownvote',
            name='vote',
            field=models.BooleanField(choices=[(True, 'Up Vote'), (False, 'Down Vote')], default=False, verbose_name='vote'),
        ),
    ]
