# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170515_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reunion_theme',
            field=models.TextField(blank=True, null=True, verbose_name='reunion theme'),
        ),
    ]
