# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_room_reunion_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length='300', verbose_name='question'),
        ),
    ]
