# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170619_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='is priority'),
        ),
    ]
