RESPONSE_API = [
  {
    "txtTituloReuniao": "Seminário  (semipresencial)",
    "txtTemaReuniao": "",
    "txtTemaResumido": "Alfabetização",
    "txtSiglaOrgao": "CE",
    "txtApelido": "EDUCAÇÃO",
    "txtNomeOrgao": "Comissão de Educação",
    "txtNomeSubcomissao": "",
    "bolSubcomissao": False,
    "codReuniao": 63610,
    "codReuniaoPrincipal": 63610,
    "codOrgao": 2009,
    "bolReuniaoConjunta": 0,
    "codEstadoReuniao": 3,
    "txtTipoReuniao": "Seminário",
    "txtObjeto": "TEMA\r\n“Alfabetização”\r\nREQ nº 167/21, de autoria do Deputado Diego Garcia.\r\n\r\nConvidados:\r\n\r\n1ª Mesa\r\n\r\nCARLOS FRANCISCO DE PAULA NADALIM - presença confirmada\r\nSecretário de Alfabetização do Ministério da Educação - Sealf/MEC\r\n\r\nMAURO LUIZ RABELO - presença confirmada\r\nSecretário de Educação Básica do Ministério da Educação - SEB/MEC\r\n\r\nSUELY MELO DE CASTRO MENEZES - presença confirmada\r\nPresidente da Câmara de Educação Básica do Conselho Nacional de Educação - CNE/MEC\r\n\r\nMARCIA BALDINI - presença confirmada\r\nDirigente Municipal de Educação em Cascavel/ PR e Presidente da Seccional da União Nacional dos Dirigentes Municipais de Educação (Undime) no Paraná \r\n\r\n2ª Mesa\r\n\r\nILONA BECSKEHÁZY - presença confirmada\r\nEx-Secretária de Educação Básica do Ministério de Educação\r\n\r\nJOÃO BATISTA ARAÚJO E OLIVEIRA - presença confirmada\r\nProfessor e Presidente do Instituto Alfa e Beto\r\n\r\nCLÁUDIA BORGES COSTA - presença confirmada\r\nRepresentante do Fórum Goiano de Educação de Jovens Adultos (EJA) e representante dos Fóruns de EJA do Centro-Oeste\r\n \r\nALESSANDRA GOTUZO SEABRA - presença confirmada\r\nProfessora do Programa de Pós-Graduação em Distúrbios do Desenvolvimento da Universidade Presbiteriana Mackenzie\r\n\r\nPEDRO ZANY CALDEIRA - presença confirmada\r\nProfessor Adjunto da Universidade Federal do Triângulo Mineiro\r\n\r\nORGANIZADO POR:\r\n\r\nComissão de Educação - CE\r\n",
    "datReuniao": 1635940800000,
    "codParticipacao": 0,
    "txtLocal": "Anexo II, Plenário 12",
    "numReuniao": 0,
    "txtInicioApos": None,
    "txtEstadoReuniao": "Encerrada (Final)        ",
    "codTipoOrgao": 2,
    "codTipoReuniao": None,
    "codArquivoTeorPauta": 2089135,
    "codArquivoTeorResultado": 2099725,
    "codArquivoTeorAta": 0,
    "codArquivoTeorTermo": 0,
    "bolTransmissaoEmAndamento": 0,
    "indTransmissaoVideo": True,
    "codLocalSisAudio": 16,
    "codLocalSisAudioPrevisto": 16,
    "txtLocalSisAudio": "Anexo II, Plenário 12",
    "datSisAudio": "03/11/2021 09:14:13",
    "codSitaq": None,
    "codAudio": 548715,
    "totReuniaoSisaudio": 1,
    "bolPublicaObjeto": True,
    "bolPainelEletronico": None,
    "numMilissegundosAjuste": 0,
    "bolExisteVideo": True,
    "qtdVotacoesEletronica": None,
    "bolHabilitarEventoInterativo": True,
    "idYoutube": "WApn9xXjCWI",
    "codEstadoTransmissaoYoutube": 3,
    "datInicio": 1635941658810,
    "datTermino": 1635956058000,
    "bolHabilitaApp": None,
    "bolSalaVirtual": None,
    "datReuniaoString": "03/01/2022 09:00:00",
    "datReuniaoFormatado": "03/01/2022",
    "horaReuniaoFormatado": "09:00:00",
    "indOrdinaria": None,
    "datInicioString": "03/01/2022 09:14:18",
    "datInicioFormatado": "03/01/2022",
    "horaInicioFormatado": "09:14:18",
    "datTerminoString": "03/01/2022 13:14:18",
    "datTerminoFormatado": "03/01/2022",
    "horaTerminoFormatado": "13:14:18"
  },
  {
    "txtTituloReuniao": "Seminário - Conjunto das Comissões CDHM, CE, CIDOSO e CLP (semipresencial)",
    "txtTemaReuniao": "",
    "txtTemaResumido": "Fraternidade e Amizade Social: 1 Ano da Carta Encíclica Fratelli Tutti",
    "txtSiglaOrgao": "CLP",
    "txtApelido": "LEGISLAÇÃO PARTICIPATIVA",
    "txtNomeOrgao": "Comissão de Legislação Participativa",
    "txtNomeSubcomissao": "",
    "bolSubcomissao": False,
    "codReuniao": 63808,
    "codReuniaoPrincipal": 63808,
    "codOrgao": 5438,
    "bolReuniaoConjunta": 1,
    "codEstadoReuniao": 8,
    "txtTipoReuniao": "Seminário",
    "txtObjeto": "TEMA:'Fraternidade e Amizade Social: 1 Ano da Carta Encíclica Fratelli Tutti'\r\nREUNIÃO CONJUNTA\r\nORGANIZADO POR:",
    "datReuniao": 1636390800000,
    "codParticipacao": 0,
    "txtLocal": "Anexo II, Plenário 06",
    "numReuniao": 0,
    "txtInicioApos": None,
    "txtEstadoReuniao": "Encerrada (Final)        ",
    "codTipoOrgao": 2,
    "codTipoReuniao": None,
    "codArquivoTeorPauta": 2095039,
    "codArquivoTeorResultado": 2106677,
    "codArquivoTeorAta": 0,
    "codArquivoTeorTermo": 0,
    "bolTransmissaoEmAndamento": 0,
    "indTransmissaoVideo": True,
    "codLocalSisAudio": 10,
    "codLocalSisAudioPrevisto": 10,
    "txtLocalSisAudio": "Anexo II, Plenário 06",
    "datSisAudio": "08/02/2022 14:20:06",
    "codSitaq": None,
    "codAudio": 548765,
    "totReuniaoSisaudio": 1,
    "bolPublicaObjeto": True,
    "bolPainelEletronico": None,
    "numMilissegundosAjuste": 0,
    "bolExisteVideo": True,
    "qtdVotacoesEletronica": None,
    "bolHabilitarEventoInterativo": True,
    "idYoutube": "a4Ep9sYCsU8",
    "codEstadoTransmissaoYoutube": 2,
    "datInicio": 1636392017980,
    "datTermino": 1636404298000,
    "bolHabilitaApp": None,
    "bolSalaVirtual": None,
    "datReuniaoString": "08/02/2022 14:00:00",
    "datReuniaoFormatado": "08/02/2022",
    "horaReuniaoFormatado": "14:00:00",
    "indOrdinaria": None,
    "datInicioString": "08/02/2022 14:20:17",
    "datInicioFormatado": "08/02/2022",
    "horaInicioFormatado": "14:20:17",
    "datTerminoString": "08/02/2022 17:44:58",
    "datTerminoFormatado": "08/02/2022",
    "horaTerminoFormatado": "17:44:58"
  },
  {
    "txtTituloReuniao": "Painel",
    "txtTemaReuniao": "",
    "txtTemaResumido": "Pacto. 3. Desafios - Orçamento",
    "txtSiglaOrgao": "SEMULHER",
    "txtApelido": "SECRETARIA DA MULHER",
    "txtNomeOrgao": "Secretaria da Mulher",
    "txtNomeSubcomissao": "",
    "bolSubcomissao": False,
    "codReuniao": 62390,
    "codReuniaoPrincipal": 62390,
    "codOrgao": 537239,
    "bolReuniaoConjunta": 0,
    "codEstadoReuniao": 5,
    "txtTipoReuniao": "Painel",
    "txtObjeto": 'TEMA:"Pacto. 3. Desafios - Orçamento"',
    "datReuniao": 1646744400000,
    "codParticipacao": 0,
    "txtLocal": "A Definir",
    "numReuniao": 0,
    "txtInicioApos": None,
    "txtEstadoReuniao": "Convocada                ",
    "codTipoOrgao": 15,
    "codTipoReuniao": None,
    "codArquivoTeorPauta": 2044276,
    "codArquivoTeorResultado": 0,
    "codArquivoTeorAta": 0,
    "codArquivoTeorTermo": 0,
    "bolTransmissaoEmAndamento": 0,
    "indTransmissaoVideo": False,
    "codLocalSisAudio": 0,
    "codLocalSisAudioPrevisto": 2,
    "txtLocalSisAudio": "A Definir",
    "datSisAudio": "",
    "codSitaq": None,
    "codAudio": 0,
    "totReuniaoSisaudio": 0,
    "bolPublicaObjeto": True,
    "bolPainelEletronico": None,
    "numMilissegundosAjuste": 0,
    "bolExisteVideo": False,
    "qtdVotacoesEletronica": None,
    "bolHabilitarEventoInterativo": True,
    "idYoutube": None,
    "codEstadoTransmissaoYoutube": 0,
    "datInicio": None,
    "datTermino": None,
    "bolHabilitaApp": None,
    "bolSalaVirtual": None,
    "indOrdinaria": None,
    "datReuniaoString": "08/03/2022 10:00:00",
    "datReuniaoFormatado": "08/03/2022",
    "horaReuniaoFormatado": "10:00:00",
    "datInicioString": "",
    "datInicioFormatado": "",
    "horaInicioFormatado": "",
    "datTerminoString": "",
    "datTerminoFormatado": "",
    "horaTerminoFormatado": ""
  }
]