name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build the stack
        run: docker-compose up -d

      - name: Generate coverage report
        run: docker-compose exec -T web sh -c "pytest --cov-report=xml term-missing --cov=./"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: codecov-umbrella
          verbose: true