name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Build the stack
        run: docker-compose up -d

      - name: Generate coverage report
        run: docker-compose exec -T web sh -c "pytest --cov-report=xml --cov=apps"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          name: codecov-umbrella
          verbose: true